### ISSUE TITLE
Move to Multiformats?

### ISSUE THREAD

**Issue by RichardLitt** [NeoTeo/SwiftMultihash#2]
Hey @NeoTeo!

Thanks so much for this. As you may know, we recently created the [Multiformats](//github.com/multiformats) organization to be a home for all of the multiformats - multiaddr, multihash, etc. Would you be interested in moving this repository to that organization? You would still have admin rights on the repository, but it would be a part of a wider organization. This would mean more relevant eyes on it (most likely) and better cross-repository issue tracking. We'd also add a line mentioning you as the original author, and of course your commits would stay the same. 

Of course, keeping it on your profile is also cool; we'll still link to this from the main multihash repository at github.com/multiformats/multihash.

Thanks for taking the time to read this. 👍 

Tracking issue, here: https://github.com/multiformats/multiformats/issues/4.

**Comment by NeoTeo** [comment]
Sure thing, though it would be really nice if it got me added to the IPFS organisation :) 
For some reason handing over the swift-ipfs repo didn't do it.

**Comment by NeoTeo** [comment]
Should I transfer it to you (I don't have rights to transfer it to multiformats apparently)?

**Comment by RichardLitt** [comment]
Yeah; I'll transfer it over, if you transfer it to me. I'm not sure why it's asking you to be an admin of multiformats to do that. Then I'll add you as an admin for this repo. Sound good?

**Comment by NeoTeo** [comment]
Not sure either. It gives me this: 
![screen shot 2016-08-06 at 11 21 31](https://cloud.githubusercontent.com/assets/882269/17455954/110816ce-5bc8-11e6-8cf4-8977572dbf42.png)

As far as being added the org, I was referring to the [IPFS organisation](https://github.com/ipfs). 
As a freelancer my profile is an important place to see my work, and moving it makes it disappear. This is a disadvantage that would be partially balanced by having a visible link to the organisations where my work has moved to.

**Comment by RichardLitt** [comment]
@NeoTeo That is a very fair point. I'll see what I can do!

**Comment by RichardLitt** [comment]
The multiformat would be part of the multiformats organization, not the IPFS one. I can add you to multiformats easily enough; is that OK?

**Comment by RichardLitt** [comment]
Added.

**Comment by NeoTeo** [comment]
For the SwiftMultiaddr and SwiftMultihash that's great, thanks :) 
I would greatly appreciate if the swift-ipfs-api, which is arguably the more important project, was also discoverable from my profile.

**Comment by RichardLitt** [comment]
Will work on that! For now, closing this issue, as this is moved. Thank you, @NeoTeo!

**Comment by NeoTeo** [comment]
Thank you @RichardLitt & @whyrusleeping  ! 

\o/ <3
