### ISSUE TITLE
Fix Tests

### ISSUE THREAD

**Issue by RichardLitt** [NeoTeo/SwiftMultihash#6]
Currently, Travis is enabled for this repository, but the tests don't have a Rakefile or a `.travis.yml` file to point to, so they fail. Oughtn't there to be a test suite for this repo? What should those tests have? 

Started conversation in https://github.com/multiformats/SwiftMultihash/pull/5.

**Comment by NeoTeo** [comment]
I've never used Travis. I'm assuming it was enabled when I transferred the repo across to multiformats.

**Comment by RichardLitt** [comment]
Would you be interested in adding unit tests to this repo, at some point? No rush, of course.

**Comment by NeoTeo** [comment]
There are lots of unit tests as part of the project, just not Travis. I won't have the time to spend getting into Travis at the moment but won't rule it out at some point.

**Comment by RichardLitt** [comment]
Cool. I'll leave this up to you to close this or not, then. Feel free to ignore tests in the PR; you're the cap'n, cap'n.

**Comment by NeoTeo** [comment]
Aye aye.
