### ISSUE TITLE
Fails to build with Xcode 10.

### ISSUE THREAD

**Issue by matijakregar** [NeoTeo/SwiftMultihash#8]
I'm using Xcode 10 and have included the `ipsf/ipfs-swift-api` in my project using Carthage (v0.30.1).
The `carthage update --platform iOS` fails with the `Building scheme "SwiftMultihash" in SwiftMultihash.xcodeproj` phase.

I investigated a bit further and found that the problem is with the `module.map` for `CommonCrypto`.
Removing the `module.map` seems to solve the build issue, but i'm not sure how this affects the framework functionality.

Could you please investigate this issue?

**Comment by matijakregar** [comment]
Tried to build with Xcode 9.4.1 and it works.

This seems to explain the situation: https://stackoverflow.com/a/42852743

**Comment by NeoTeo** [comment]
Fixed.
Thanks for contributing.

:) Teo
